### ISSUE TITLE
Error and disabling on startup

### ISSUE THREAD

**Issue by RhythmicSys** [Remynfv/EmojiTab#1]
Not entirely sure if this is an issue  with the plugin or protocolLib but it seems that there's an issue on startup on 1.19.3

<details>
  <summary>Stack Trace</summary>

```console
[20:52:01 INFO]: [EmojiTab] Enabling EmojiTab v1.0-SNAPSHOT
[20:52:01 INFO]: [EmojiTab] > Loaded!
[20:52:01 INFO]: [EmojiTab] > WARN: Emoji name ':heart_exclamation:' is over 16 characters and will be trimmed!
[20:52:01 ERROR]: Error occurred while enabling EmojiTab v1.0-SNAPSHOT (Is it up to date?)
com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
	at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:316) ~[ProtocolLib.jar:?]
	at com.comphenix.packetwrapper.WrapperPlayServerPlayerInfo.setAction(WrapperPlayServerPlayerInfo.java:45) ~[EmojiTab.jar:?]
	at com.github.remynfv.emojitab.EmojiTab.generateEmojiPackets(EmojiTab.kt:130) ~[EmojiTab.jar:?]
	at com.github.remynfv.emojitab.EmojiTab.reloadConfigs(EmojiTab.kt:209) ~[EmojiTab.jar:?]
	at com.github.remynfv.emojitab.EmojiTab.onEnable(EmojiTab.kt:114) ~[EmojiTab.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:372) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:550) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:631) ~[purpur-1.19.3.jar:git-Purpur-1916]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:544) ~[purpur-1.19.3.jar:git-Purpur-1916]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[purpur-1.19.3.jar:git-Purpur-1916]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[purpur-1.19.3.jar:git-Purpur-1916]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:344) ~[purpur-1.19.3.jar:git-Purpur-1916]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1916]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1916]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:52:01 INFO]: [EmojiTab] Disabling EmojiTab v1.0-SNAPSHOT
```
</details>

<details>
<summary>Startup Log</summary>

```console
[20:51:51] [ServerMain/INFO]: Building unoptimized datafixer
[20:51:52] [ServerMain/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[20:51:53] [ServerMain/INFO]: Loaded 7 recipes
[20:51:54] [Server thread/INFO]: Starting minecraft server version 1.19.3
[20:51:54] [Server thread/INFO]: Loading properties
[20:51:54] [Server thread/INFO]: This server is running Purpur version git-Purpur-1916 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 41593ba on HEAD)
[20:51:55] [Server thread/INFO]: Server Ping Player Sample Count: 12
[20:51:55] [Server thread/INFO]: Using 4 threads for Netty based IO
[20:51:55] [Server thread/INFO]: [ChunkTaskScheduler] Chunk system is using 1 I/O threads, 3 worker threads, and gen parallelism of 3 threads
[20:51:55] [Server thread/INFO]: [Pufferfish] Max SIMD vector size on this system is 256 bits (int)
[20:51:55] [Server thread/INFO]: [Pufferfish] Max SIMD vector size on this system is 256 bits (float)
[20:51:55] [Server thread/INFO]: [Pufferfish] SIMD operations detected as functional. Will replace some operations with faster versions.
[20:51:55] [Server thread/INFO]: Default game type: SURVIVAL
[20:51:55] [Server thread/INFO]: Generating keypair
[20:51:56] [Server thread/INFO]: Starting Minecraft server on *:25565
[20:51:56] [Server thread/INFO]: Using epoll channel type
[20:51:56] [Server thread/INFO]: Paper: Using libdeflate (Linux x86_64) compression from Velocity.
[20:51:56] [Server thread/INFO]: Paper: Using OpenSSL 3.0.x (Linux x86_64) cipher from Velocity.
[20:51:57] [Server thread/INFO]: [LuckPerms] Loading LuckPerms v5.4.62
[20:51:57] [Server thread/INFO]: [SimpleBucketMobs] Loading SimpleBucketMobs vdev
[20:51:57] [Server thread/INFO]: [spark] Loading spark v1.10.30
[20:51:57] [Server thread/INFO]: [AdvancedGift] Loading AdvancedGift v1.11.1
[20:51:57] [Server thread/INFO]: [ProtocolLib] Loading ProtocolLib v5.0.0-SNAPSHOT-b614
[20:51:58] [Server thread/INFO]: [EmojiTab] Loading EmojiTab v1.0-SNAPSHOT
[20:51:58] [Server thread/INFO]: Server permissions file permissions.yml is empty, ignoring it
[20:51:58] [Server thread/INFO]: [LuckPerms] Enabling LuckPerms v5.4.62
[20:51:58] [Server thread/INFO]:         __    
[20:51:58] [Server thread/INFO]:   |    |__)   LuckPerms v5.4.62
[20:51:58] [Server thread/INFO]:   |___ |      Running on Bukkit - Purpur
[20:51:58] [Server thread/INFO]: 
[20:51:58] [Server thread/INFO]: [LuckPerms] Loading configuration...
[20:51:59] [Server thread/INFO]: [LuckPerms] Loading storage provider... [H2]
[20:51:59] [Server thread/INFO]: [LuckPerms] Loading internal permission managers...
[20:51:59] [Server thread/INFO]: [LuckPerms] Performing initial data load...
[20:51:59] [Server thread/INFO]: [LuckPerms] Successfully enabled. (took 1104ms)
[20:51:59] [Server thread/INFO]: [ProtocolLib] Enabling ProtocolLib v5.0.0-SNAPSHOT-b614
[20:51:59] [Server thread/INFO]: Preparing level "world"
[20:52:00] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[20:52:00] [Server thread/INFO]: Time elapsed: 131 ms
[20:52:00] [Server thread/INFO]: Preparing start region for dimension minecraft:the_nether
[20:52:00] [Server thread/INFO]: Time elapsed: 57 ms
[20:52:00] [Server thread/INFO]: Preparing start region for dimension minecraft:the_end
[20:52:00] [Server thread/INFO]: Time elapsed: 64 ms
[20:52:00] [Server thread/INFO]: [SimpleBucketMobs] Enabling SimpleBucketMobs vdev
[20:52:00] [Server thread/WARN]: [SimpleBucketMobs] Invalid Mob Type in config.yml: CAVESPIDER
[20:52:00] [Server thread/WARN]: [SimpleBucketMobs] Invalid Mob Type in config.yml: FISH
[20:52:00] [Server thread/WARN]: [SimpleBucketMobs] Invalid Mob Type in config.yml: GOLEM
[20:52:00] [Server thread/WARN]: [SimpleBucketMobs] Invalid Mob Type in config.yml: ILLAGER
[20:52:00] [Server thread/WARN]: [SimpleBucketMobs] Invalid Mob Type in config.yml: STEERABLE
[20:52:00] [Server thread/INFO]: [spark] Enabling spark v1.10.30
[20:52:01] [Server thread/INFO]: [spark] Using Paper ServerTickStartEvent for tick monitoring
[20:52:01] [Server thread/INFO]: [spark] Starting background profiler...
[20:52:01] [Server thread/INFO]: [AdvancedGift] Enabling AdvancedGift v1.11.1
[20:52:01] [Server thread/INFO]: [AdvancedGift] ===================================================
[20:52:01] [Server thread/INFO]: [AdvancedGift] Checking server version  ------------------
[20:52:01] [Server thread/INFO]: [AdvancedGift] NMS Version used: v1_19_R2
[20:52:01] [Server thread/INFO]: [AdvancedGift] 
[20:52:01] [Server thread/INFO]: [AdvancedGift] This version is supported!
[20:52:01] [Server thread/INFO]: [AdvancedGift] 
[20:52:01] [Server thread/INFO]: [AdvancedGift] Loading files  --------------------
[20:52:01] [Server thread/INFO]: [AdvancedGift] Config loaded.
[20:52:01] [Server thread/INFO]: [AdvancedGift] Player info loaded.
[20:52:01] [Server thread/INFO]: [AdvancedGift] 
[20:52:01] [Server thread/INFO]: [AdvancedGift] Searching for a material library  -----------------
[20:52:01] [Server thread/INFO]: [AdvancedGift] No supported material library found.
[20:52:01] [Server thread/INFO]: [AdvancedGift] Spigot's material enum will be used instead.
[20:52:01] [Server thread/INFO]: [AdvancedGift] ===================================================
[20:52:01] [Server thread/INFO]: [EmojiTab] Enabling EmojiTab v1.0-SNAPSHOT
[20:52:01] [Server thread/INFO]: [EmojiTab] > Loaded!
[20:52:01] [Server thread/INFO]: [EmojiTab] > WARN: Emoji name ':heart_exclamation:' is over 16 characters and will be trimmed!
[20:52:01] [Server thread/ERROR]: Error occurred while enabling EmojiTab v1.0-SNAPSHOT (Is it up to date?)
com.comphenix.protocol.reflect.FieldAccessException: Field index 0 is out of bounds for length 0
	at com.comphenix.protocol.reflect.FieldAccessException.fromFormat(FieldAccessException.java:49) ~[ProtocolLib.jar:?]
	at com.comphenix.protocol.reflect.StructureModifier.write(StructureModifier.java:316) ~[ProtocolLib.jar:?]
	at com.comphenix.packetwrapper.WrapperPlayServerPlayerInfo.setAction(WrapperPlayServerPlayerInfo.java:45) ~[EmojiTab.jar:?]
	at com.github.remynfv.emojitab.EmojiTab.generateEmojiPackets(EmojiTab.kt:130) ~[EmojiTab.jar:?]
	at com.github.remynfv.emojitab.EmojiTab.reloadConfigs(EmojiTab.kt:209) ~[EmojiTab.jar:?]
	at com.github.remynfv.emojitab.EmojiTab.onEnable(EmojiTab.kt:114) ~[EmojiTab.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:372) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:550) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:631) ~[purpur-1.19.3.jar:git-Purpur-1916]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:544) ~[purpur-1.19.3.jar:git-Purpur-1916]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:640) ~[purpur-1.19.3.jar:git-Purpur-1916]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:439) ~[purpur-1.19.3.jar:git-Purpur-1916]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:344) ~[purpur-1.19.3.jar:git-Purpur-1916]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1117) ~[purpur-1.19.3.jar:git-Purpur-1916]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1916]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[20:52:01] [Server thread/INFO]: [EmojiTab] Disabling EmojiTab v1.0-SNAPSHOT
[20:52:01] [Server thread/WARN]: Could not register alias sp because it contains commands that do not exist: simpleprefixes:simpleprefix $1-
[20:52:02] [Server thread/INFO]: Running delayed init tasks
[20:52:02] [Server thread/INFO]: Done (7.363s)! For help, type "help"
[20:52:57] [Server thread/INFO]: Stopping the server
[20:52:57] [Server thread/INFO]: Stopping server
[20:52:57] [Server thread/INFO]: [ProtocolLib] Disabling ProtocolLib v5.0.0-SNAPSHOT-b614
[20:52:57] [Server thread/INFO]: [AdvancedGift] Disabling AdvancedGift v1.11.1
[20:52:57] [Server thread/INFO]: [AdvancedGift] Saving playerinfo.json.
[20:52:57] [Server thread/INFO]: [spark] Disabling spark v1.10.30
[20:52:57] [Server thread/INFO]: [SimpleBucketMobs] Disabling SimpleBucketMobs vdev
[20:52:57] [Server thread/INFO]: [LuckPerms] Disabling LuckPerms v5.4.62
[20:52:57] [Server thread/INFO]: [LuckPerms] Starting shutdown process...
[20:52:57] [Server thread/INFO]: [LuckPerms] Closing storage...
[20:52:57] [Server thread/INFO]: [LuckPerms] Goodbye!
[20:52:57] [Server thread/INFO]: Saving players
[20:52:57] [Server thread/INFO]: Saving worlds
[20:52:57] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[20:52:57] [Server thread/INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world'
[20:52:57] [Server thread/INFO]: [ChunkHolderManager] Halted chunk system for world 'world'
[20:52:57] [Server thread/INFO]: [ChunkHolderManager] Saving all chunkholders for world 'world'
[20:52:58] [Server thread/INFO]: [ChunkHolderManager] Saved 529 block chunks, 529 entity chunks, 0 poi chunks in world 'world' in 1.50s
[20:52:59] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[20:52:59] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_nether]'/minecraft:the_nether
[20:52:59] [Server thread/INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world_nether'
[20:52:59] [Server thread/INFO]: [ChunkHolderManager] Halted chunk system for world 'world_nether'
[20:52:59] [Server thread/INFO]: [ChunkHolderManager] Saving all chunkholders for world 'world_nether'
[20:52:59] [Server thread/INFO]: [ChunkHolderManager] Saved 529 block chunks, 529 entity chunks, 0 poi chunks in world 'world_nether' in 0.47s
[20:53:00] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[20:53:00] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world_the_end]'/minecraft:the_end
[20:53:00] [Server thread/INFO]: [ChunkHolderManager] Waiting 60s for chunk system to halt for world 'world_the_end'
[20:53:00] [Server thread/INFO]: [ChunkHolderManager] Halted chunk system for world 'world_the_end'
[20:53:00] [Server thread/INFO]: [ChunkHolderManager] Saving all chunkholders for world 'world_the_end'
[20:53:00] [Server thread/INFO]: [ChunkHolderManager] Saved 529 block chunks, 529 entity chunks, 0 poi chunks in world 'world_the_end' in 0.08s
[20:53:00] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[20:53:00] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[20:53:00] [Server thread/INFO]: Flushing Chunk IO
[20:53:00] [Server thread/INFO]: Closing Thread Pool
[20:53:00] [Server thread/INFO]: Closing Server
```
</details>

Server Version: `git-Purpur-1916 (MC: 1.19.3)`

**Comment by FlamedDogo99** [comment]
I too have this issue.
